# Generated by Django 4.2.1 on 2023-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
