# Generated by Django 4.2.1 on 2023-06-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid_number',
            field=models.TextField(null=True),
        ),
    ]
